
title: Akka Java Tutorial
email: info@fractus.io
description: > # this means to ignore newlines until "baseurl:"
  Akka Java Tutorial.
baseurl: "/akka-tutorial" # the subpath of your site, e.g. /blog
my_setting: "/"

url: "https://fractus-io.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  fractus-io

permalink: :categories/:title
exclude: [deprecated, vendor, Gemfile, Procfile]
safe: true

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
